import type { CollectionConfig } from 'payload'

export const AffiliateReferrals: CollectionConfig = {
  slug: 'affiliate-referrals',
  admin: {
    useAsTitle: 'id',
    group: 'Affiliates',
    defaultColumns: ['affiliate', 'type', 'commission', 'status', 'createdAt'],
  },
  access: {
    read: ({ req }) => {
      if (req.user?.role === 'super-admin') return true
      const affiliateId =
        req.user?.role === 'affiliate' && typeof req.user.affiliate === 'object'
          ? req.user.affiliate?.id
          : req.user?.affiliate
      if (!affiliateId) return false
      return { affiliate: { equals: affiliateId } }
    },
    create: () => false,
    update: ({ req }) => req.user?.role === 'super-admin',
    delete: ({ req }) => req.user?.role === 'super-admin',
  },
  fields: [
    {
      name: 'affiliate',
      type: 'relationship',
      relationTo: 'affiliates',
      required: true,
    },
    {
      name: 'order',
      type: 'relationship',
      relationTo: 'orders',
      admin: { description: 'The order generated by this referral (if converted)' },
    },
    {
      name: 'type',
      type: 'select',
      required: true,
      options: [
        { label: 'Click', value: 'click' },
        { label: 'Conversion', value: 'conversion' },
      ],
    },
    {
      name: 'referralCode',
      type: 'text',
      required: true,
    },
    {
      name: 'landingUrl',
      type: 'text',
      admin: { description: 'The page the visitor landed on' },
    },
    {
      name: 'commission',
      type: 'number',
      defaultValue: 0,
      admin: { description: 'Commission earned in cents (for conversions)' },
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'pending',
      options: [
        { label: 'Pending', value: 'pending' },
        { label: 'Approved', value: 'approved' },
        { label: 'Paid', value: 'paid' },
        { label: 'Rejected', value: 'rejected' },
      ],
    },
    {
      name: 'visitorIp',
      type: 'text',
      admin: { description: 'Hashed visitor IP for dedup' },
    },
  ],
  timestamps: true,
}
